apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-operator
spec:
  replicas: 1
  template:
    spec:
      containers:
       - name: prometheus-operator
         image: quay.io/coreos/prometheus-operator:v0.0.1
         resources:
           requests:
             cpu: 100m
             memory: 50Mi
           limits:
             cpu: 200m
             memory: 300Mi
